#!/bin/bash

cat <<- EOF > /etc/logrotate.d/freepbx-qcallback
/var/log/asterisk/qcallback_*.log{
	size 50M
	missingok
	rotate 5
	notifempty
	sharedscripts
	create 0640 asterisk asterisk
	su asterisk asterisk
	postrotate
		/usr/sbin/fwconsole pm2 --reload-logs -q
	endscript
}
EOF
